// OuterPlots -- battlefield building plots outside each castle's walls,
// two bands per side:
//   "near"  -- 8 plots, in 2 groups of 4 (one above the play area's
//              vertical center, one below), close to the castle wall.
//   "far"   -- 4 plots, in 2 groups of 2 (above/below center), deeper in
//              the contested middle ground. All 4 share one x column, so
//              they read as a single vertical line split by the center gap.
// Resource buildings get a placement bonus OUTSIDE the castle (any plot
// this spawner creates); unit-training buildings get theirs INSIDE
// instead (see oPlotSpawner's grid). Everything gets a bonus on "far"
// plots -- the tradeoff for being that exposed to attack.
//
// X clearance: oUnitParent's default guardRect is ShapeRect(328,8,480,400)
// -- i.e. every guarding unit's default patrol zone spans world x:328-480.
// _nearCols starts at 512, 32px clear of that zone's right edge, so plots
// don't sit in the middle of where units are patrolling.
//
// Y spread: pushed further from the play area's vertical center (y=207,
// from InitPlayArea in RoomCreationCode.gml) than the first pass -- above
// rows sit close to the play area's top edge (y1=8), below rows close to
// the bottom edge (y2=406, RowsBelow's second row overshoots that by 2px,
// negligible).
//
// All values grid-aligned (world x/y % 48 == 32, same parity as
// oPlotSpawner's inner castle grid). Still a first pass, not IDE-verified
// -- nudge freely.
//
// Player-side coordinates are authored directly; enemy-side plots are
// generated by mirroring player_x -> room_width - player_x, matching how
// oCastleManager mirrors oPlayerCastle/oEnemyCastle off the same axis.

var _nearCols      = [512, 560];
var _rowsAbove      = [32, 80];   // both well above center y=207
var _rowsBelow      = [320, 368]; // both well below center y=207

var _farCol = 704; // single column -- both far groups share it, so all 4 far plots line up vertically

// -- Near plots: 8 per side (2 cols x 2 rows x 2 vertical groups) --
for (var i = 0; i < array_length(_nearCols); i++) {
    var _colX = _nearCols[i];

    for (var j = 0; j < array_length(_rowsAbove); j++) {
        SpawnBuildingPlot(_colX, _rowsAbove[j], false, false, TEAM.PLAYER);
        SpawnBuildingPlot(room_width - _colX, _rowsAbove[j], false, false, TEAM.ENEMY);
    }
    for (var j = 0; j < array_length(_rowsBelow); j++) {
        SpawnBuildingPlot(_colX, _rowsBelow[j], false, false, TEAM.PLAYER);
        SpawnBuildingPlot(room_width - _colX, _rowsBelow[j], false, false, TEAM.ENEMY);
    }
}

// -- Far plots: 4 per side (1 shared col x 2 rows x 2 vertical groups) --
for (var j = 0; j < array_length(_rowsAbove); j++) {
    SpawnBuildingPlot(_farCol, _rowsAbove[j], false, true, TEAM.PLAYER);
    SpawnBuildingPlot(room_width - _farCol, _rowsAbove[j], false, true, TEAM.ENEMY);
}
for (var j = 0; j < array_length(_rowsBelow); j++) {
    SpawnBuildingPlot(_farCol, _rowsBelow[j], false, true, TEAM.PLAYER);
    SpawnBuildingPlot(room_width - _farCol, _rowsBelow[j], false, true, TEAM.ENEMY);
}

instance_destroy();
